/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alquilervehiculo.vista;

import alquilervehiculo.gestion.GestionUsuario;
import alquilervehiculo.gestion.GestionVehiculo;
import alquilervehiculo.modelo.Usuario;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Camilo
 */
public class MDIVehiculo extends javax.swing.JFrame
{

    private Usuario usuarioAutenticado;
    private GestionUsuario gestionLogin;
    private GestionVehiculo controlVehiculo;

    /**
     * Creates new form MDIVehiculo
     */
    public MDIVehiculo()
    {
        initComponents();
    }

    private void iniciarMenus(boolean estado)
    {
        mnuCrearUsuario.setVisible(estado);
        mnuListarVehiculos.setVisible(estado);
        mnuPromedioVehiculos.setVisible(estado);
        mnuBuscarVehiculo.setVisible(estado);

    }

    private void gestionarPermisosMenu()
    {
        switch (usuarioAutenticado.getTipoUsuario().getCodigo())
        {
            //Administrador
            case 1:
                iniciarMenus(true);
                break;
            //Usuario
            case 2:
                iniciarMenus(false);
                mnuBuscarVehiculo.setVisible(true);
                break;
            // Otro
//            case3:
//            break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        txtCorreoUsuario = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JToggleButton();
        menuBar = new javax.swing.JMenuBar();
        mnuVehiculo = new javax.swing.JMenu();
        mnuListarVehiculos = new javax.swing.JMenuItem();
        mnuCrearUsuario = new javax.swing.JMenuItem();
        mnuPromedioVehiculos = new javax.swing.JMenuItem();
        mnuBuscarVehiculo = new javax.swing.JMenuItem();
        mnuCerrarSesion = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtContrasenia.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtContraseniaActionPerformed(evt);
            }
        });

        jLabel1.setText("*Correo Electronico");

        jLabel2.setText("*Contraseña");

        jLabel3.setText("ALQUILER DE VEHÍCULOS");

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(390, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCorreoUsuario)
                                .addComponent(txtContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnIngresar)
                        .addGap(131, 131, 131))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel3)
                .addGap(0, 297, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCorreoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIngresar)
                .addGap(47, 47, 47))
        );

        desktopPane.add(jPanel1);
        jPanel1.setBounds(0, 0, 670, 520);

        mnuVehiculo.setMnemonic('f');
        mnuVehiculo.setText("Archivo");
        mnuVehiculo.setEnabled(false);

        mnuListarVehiculos.setMnemonic('o');
        mnuListarVehiculos.setText("Listar Vehículos");
        mnuListarVehiculos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuListarVehiculosActionPerformed(evt);
            }
        });
        mnuVehiculo.add(mnuListarVehiculos);

        mnuCrearUsuario.setMnemonic('s');
        mnuCrearUsuario.setText("Crear Usuario");
        mnuCrearUsuario.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuCrearUsuarioActionPerformed(evt);
            }
        });
        mnuVehiculo.add(mnuCrearUsuario);

        mnuPromedioVehiculos.setMnemonic('a');
        mnuPromedioVehiculos.setText("Reporte promedio");
        mnuVehiculo.add(mnuPromedioVehiculos);

        mnuBuscarVehiculo.setText("Buscar Vehículo");
        mnuVehiculo.add(mnuBuscarVehiculo);

        mnuCerrarSesion.setText("Cerrar Sesión");
        mnuCerrarSesion.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuCerrarSesionActionPerformed(evt);
            }
        });
        mnuVehiculo.add(mnuCerrarSesion);

        mnuSalir.setMnemonic('x');
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuVehiculo.add(mnuSalir);

        menuBar.add(mnuVehiculo);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuListarVehiculosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuListarVehiculosActionPerformed
    {//GEN-HEADEREND:event_mnuListarVehiculosActionPerformed

    }//GEN-LAST:event_mnuListarVehiculosActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnIngresarActionPerformed
    {//GEN-HEADEREND:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        if (txtCorreoUsuario.getText() == null || txtCorreoUsuario.getText().compareTo("") == 0)
        {
            JOptionPane.showMessageDialog(this,
                "Debe diligenciar el correo", "Datos Faltantes", 2);
        }
        else if (txtContrasenia.getPassword().length == 0)
        {
            JOptionPane.showMessageDialog(this,
                "Debe diligenciar la contraseña", "Datos Faltantes", 2);
        }
        else
        {
            gestionLogin = new GestionUsuario();

            //Significa que diligencio correo y contraseña
            Pattern pattern = Pattern.compile("^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$");
            Matcher matcher = pattern.matcher(txtCorreoUsuario.getText());

            if (matcher.find() == true)
            {
                usuarioAutenticado = gestionLogin.validarUsuario(txtCorreoUsuario.getText(), txtContrasenia.getText());
                if (usuarioAutenticado == null)
                {
                    JOptionPane.showMessageDialog(this,
                        "Datos Erróneos", "Datos Erróneos", 0);
                }
                else
                {
                    controlVehiculo = new GestionVehiculo();
                    String nombreUsr = usuarioAutenticado.getNombre().toUpperCase();

                    JOptionPane.showMessageDialog(this,
                        "Bienvenido " + nombreUsr, "Bienvenido", 1);
                    mnuVehiculo.setEnabled(true);
                    gestionarPermisosMenu();
                    //                    jfrmLogin.hide();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this,
                    "El correo no tiene un formato válido", "Datos Erróneos", 0);
            }
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtContraseniaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtContraseniaActionPerformed
    {//GEN-HEADEREND:event_txtContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseniaActionPerformed

    private void mnuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuCerrarSesionActionPerformed
    {//GEN-HEADEREND:event_mnuCerrarSesionActionPerformed
        // TODO add your handling code here:
        mnuVehiculo.setEnabled(false);
        txtCorreoUsuario.setText("");
        txtContrasenia.setText("");
        usuarioAutenticado = null;
        iniciarMenus(false);
       // jfrmLogin.show();
    }//GEN-LAST:event_mnuCerrarSesionActionPerformed

    private void mnuCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuCrearUsuarioActionPerformed
    {//GEN-HEADEREND:event_mnuCrearUsuarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnuCrearUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MDIVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MDIVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MDIVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MDIVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MDIVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnIngresar;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuBuscarVehiculo;
    private javax.swing.JMenuItem mnuCerrarSesion;
    private javax.swing.JMenuItem mnuCrearUsuario;
    private javax.swing.JMenuItem mnuListarVehiculos;
    private javax.swing.JMenuItem mnuPromedioVehiculos;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenu mnuVehiculo;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtCorreoUsuario;
    // End of variables declaration//GEN-END:variables

}
